direction: right

(** -> **)[*].style.stroke-width: 2
(** -> **)[*].style.animated: true

Client: {
  icon: "https://cdn-icons-png.flaticon.com/512/1851/1851160.png"
}

secretmanager: {
  label: "Secret Manager"
  icon: https://www.svgrepo.com/show/375492/secret-manager.svg
  near: top-center
}

api_gateway: {
  label: "API Gateway"
  icon: https://cdn-icons-png.flaticon.com/512/10169/10169724.png

  auth_service: {
    label: "Authentication Service"
    icon: https://cdn-icons-png.flaticon.com/512/6357/6357632.png
  }

  auth_database: {
    label: "Authentication Database"
    icon: https://cdn-icons-png.flaticon.com/512/9850/9850812.png
  }

  auth_service -> auth_database: "Authenticate\nor\nValidate token"
}

secretmanager --> api_gateway.auth_service: "Secret"

service_a: {
  label: "Service A"
  icon: https://cdn-icons-png.flaticon.com/512/6357/6357632.png
}

service_b: {
  label: "Service B"
  icon: https://cdn-icons-png.flaticon.com/512/6357/6357632.png
}

db_a: {
  label: "Database A"
  icon: https://cdn-icons-png.flaticon.com/512/9850/9850812.png
}

db_b: {
  label: "Database B"
  icon: https://cdn-icons-png.flaticon.com/512/9850/9850812.png
}

client -> api_gateway: "Authenticate\n{username, password}"
api_gateway -> client: "Response Authenticate\n{access_token, refresh_token}"

client -> api_gateway: "Requests\n{access_token}"
api_gateway -> client: "Response Requests\n{data}"

api_gateway -> service_a: "Route requests\nwith User ID"
api_gateway -> service_b: "Route requests\nwith User ID"

service_a -> db_a: "Query data"
service_b -> db_b: "Query data"
