
khu_vuc_tu_hinh{
    label: "Khu vực tử hình"

    public_camera{
        label: "Public Camera"
    }


    roof_holding_room{
        label: "Mái nhà của phòng giam"
        tech_box2{
            label: "Hộp kĩ thuật 2"
        } 
    }
  
    
    spiritual_room{
        label: "Phòng quản giáo"
        tech_box1{
            label: "Hộp kĩ thuật 1"
        }

        tech_box2{
            label: "Hộp kĩ thuật 2"
        }
    }

    public_camera -> roof_holding_room.tech_box2
    grid-rows:2
}

khu_vuc_giam_giu{
    label: "Khu vực giam giữ"
    note: |md
    - Phòng 20-30 đối tượng
    - 1-2 cameras
         - Khu nữ có 2 camera
         - Khu nam có 1 camera
    - Có camera hành lang và sân chơi
  |


    spiritual_room{
        label: "Phòng quản giáo"
        tech_box1{
            label: "Hộp kĩ thuật 1"
        }

        tech_box2{
            label: "Hộp kĩ thuật 2"
        }
    }
    public_camera {
        label: "Public Camera"
    }

    tech_room{
        label: "Phòng kĩ thuật"
        tech_box1{
            label: "Hộp kĩ thuật 1"
        }

        tech_box2{
            label: "Hộp kĩ thuật 2"
        }
    }

    public_camera -> tech_room.tech_box1 : {
        style.stroke-dash: 4
    }
    public_camera -> spiritual_room.tech_box1 : {
        style.stroke-dash: 4
    }

    grid-rows:4

}

khu_vuc_tam_giam{
    label: "Khu vực tạm giam"
    tech_room{
        label: "Phòng kĩ thuật"
    
        tech_box1{
            label: "Hộp kĩ thuật 1"
        }
    
        tech_box2{
            label: "Hộp kĩ thuật 2"
        }
    
        tech_box3{
            label: "Hộp kĩ thuật 3"
        }
    
    
    }


    hiden_camera{
        label: "Hidden Camera"
    }
    
    public_camera{
        label: "Public Camera"
    }

    hiden_camera -> tech_room.tech_box1
    public_camera -> tech_room.tech_box2
}



center_information_room{
    label: "Phòng thông tin trung tâm"

    nas_storage{
        label: "NAS Storage"
    }

    pc{
        label: "PC"
    }

    ai_agent_crew{
        label: "AI Agent Crew ~ (40 boxes or xx Servers GPU)"
    }

    server_master_services{
        label: "Server Master Services"
    }

    training_servers{
        label: "Training Servers"
    }

    nas_storage -> pc : "Read mp4 files"
    
    nas_storage -> ai_agent_crew : "Store AI models"

    master_service -> ai_agent_crew: "Control boxes"

    # grid-rows: 3

}


khu_vuc_tu_hinh.roof_holding_room.tech_box2 -> center_information_room.nas_storage


khu_vuc_tam_giam.tech_room.tech_box1 -> center_information_room.nas_storage
khu_vuc_tam_giam.tech_room.tech_box2 -> center_information_room.nas_storage

khu_vuc_giam_giu.spiritual_room -> center_information_room.nas_storage
khu_vuc_giam_giu.tech_room -> center_information_room.nas_storage
