classes: {
  current_system

  milesetone_manager_server: {
    label: "2x Milestone Manager Servers"
    icon: https://ryalex.com.au/wp-content/uploads/2022/02/Website-Product-Images.png
    label.near: bottom-center
  }
}

internet_boundary: {
  label: "Internal Network"
  style: {
    fill: White
  }

  camera: {
    label: "Camera"
    icon: https://cdn-icons-png.flaticon.com/128/2642/2642550.png
    class: current_system
    style.multiple: true
    top: 0
    left: 320
  }
  current_system: {
    milesetone_manager_server.class: milesetone_manager_server

    camera_server: {
      label: "14x Camera Servers"
      style.multiple: true
      class: current_system
      NVR: {
        label: "Camera Management (NVR)"
        class: virtual_component
      }
      NAS: {
        label: "Camera Storage (NAS)"
      }

      NVR -> NAS
    }
    top: 123
    left: 0
  }
  kubernetes_cluster: {
    label: "Virtualization Server Cluster"

    master_server: {
      label: "1x Virtualization Management Server"
      icon: https://static-00.iconduck.com/assets.00/kubernetes-icon-2048x1995-r1q3f8n7.png
      class: akaCam_system
    }
    main_system: {
      label: "Main System"

      ai_cluster: {
        label: "14x Edge AI Device Cluster"
        class: akaCam_system
        style.multiple: true
      }

      ai_server: {
        label: "2x AI Servers"
        class: akaCam_system
        style.multiple: true
      }

      application_server: {
        label: "2x Application Servers"
        class: akaCam_system
        style.multiple: true
      }
      nas_storage: {
        label: "1x Storage Server"
        class: akaCam_system
      }
      grid-rows: 2
    }

    secondary_system: {
      label: "Secondary System"

      ai_cluster: {
        label: "4x Edge AI Device Cluster"
        class: akaCam_system
        style.multiple: true
      }

      ai_server: {
        label: "2x AI Servers"
        class: akaCam_system
        style.multiple: true
      }

      application_server: {
        label: "2x Application Servers"
        class: akaCam_system
        style.multiple: true
      }

      nas_storage: {
        label: "1x Storage Server"
        class: akaCam_system
      }
      grid-rows: 2
    }
    grid-rows: 3
    top: 901
    left: 0
    width: 823
    height: 915
  }

  current_system.milesetone_manager_server -> current_system.camera_server.NVR
  camera -> current_system.milesetone_manager_server
  current_system.milesetone_manager_server -> akaCam_switch
  akaCam_switch -> kubernetes_cluster

  akaCam_switch: {
    label: "akaCam Switchs"
    class: akaCam_system
    style.multiple: true
    icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
    label.near: bottom-center
    top: 725
    left: 0
    width: 823
    height: 92
  }
}
# add firewall core
