current: {
  label: "Hiện trạng"
  direction: down
  camera: {
    label: "Camera"
    icon: https://icons.terrastruct.com/essentials/012-video%20camera.svg
    style.multiple: true
    top: 0
    left: 184
    width: 835
    height: 92
    label.near: bottom-center
  }

  networking: {
    label: "Hệ thống mạng"

    switch_management: {
      label: "Switch quản lý"
      icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
      style.multiple: true
      label.near: bottom-center
      top: 0
      left: 263
      width: 178
      height: 102
    }
    switch_poe: {
      label: "Switch POE"
      icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
      style.multiple: true
      label.near: bottom-center
      top: 0
      left: 492
    }

    core_switch: {
      label: "Switch cơ sở"
      icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
      style.multiple: true
      label.near: bottom-center
      top: 239
      left: 0
      width: 677
      height: 92
    }

    switch_24_port: {
      label: "Switch 24 Port"
      icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
      style.multiple: true
      label.near: bottom-center
      top: 0
      left: 0
    }
    top: 126
    left: 184
    width: 774
    height: 478
  }

  monitor_screen: {
    label: "Màn hình theo dõi"
    icon: https://cdn-icons-png.flaticon.com/128/9926/9926868.png
    style.multiple: true
    label.near: bottom-center
    top: 799
    left: 184
    width: 835
    height: 92
  }

  camera_server: {
    label: "Máy chủ quản trị và lưu trữ camera"
    icon: https://cdn-icons-png.flaticon.com/128/2704/2704286.png
    style.multiple: true
    label.near: bottom-center
    top: 646
    left: 184
    width: 835
    height: 92
  }

  fire_wall: {
    label: "Firewall"
    icon: https://cdn-icons-png.flaticon.com/128/8475/8475441.png
    style.multiple: true
    label.near: bottom-center
    top: 0
    left: 0
    width: 129
    height: 891
  }

  camera -> networking.switch_poe
  networking.switch_poe -> networking.core_switch
  networking.core_switch -> networking.switch_management
  networking.core_switch -> networking.switch_24_port
  networking.core_switch -> camera_server
  networking.core_switch -> fire_wall
  camera_server -> monitor_screen
  top: 0
  left: 0
  width: 1177
  height: 1099
}

q_vision_overview: {
  label: QVision

  networking: {
    label: "Hệ thống mạng"
    server_switch: {
      label: "Server switch"
      icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
      style.multiple: true
      top: 351
      left: 0
    }

    switch_management: {
      label: "Switch quản lý"
      icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
      style.multiple: true
      top: 701
      left: 0
      width: 203
      height: 102
    }

    san_switch: {
      label: "SAN switch"
      icon: https://cdn-icons-png.flaticon.com/128/2729/2729174.png
      style.multiple: true
      top: 0
      left: 0
    }
    server_switch -> switch_management

    width: 191
    height: 927
    top: 0
    left: 0
  }
  virtualization_system: {
    label: "Hệ thống ảo hóa"
    icon.near: top-left
    icon: https://static-00.iconduck.com/assets.00/kubernetes-icon-2048x1995-r1q3f8n7.png
    style: {
      stroke-dash: 3
    }

    ai_server: {
      label: "Máy chủ AI lớn"
      icon: https://cdn-icons-png.flaticon.com/128/2704/2704286.png
      style.multiple: true
      label.near: bottom-center
      top: 0
      left: 0
      width: 469
      height: 102
    }

    ai_cluster: {
      label: "Cụm AI Box"
      icon: https://cdn-icons-png.flaticon.com/128/6811/6811450.png
      style.multiple: true
      label.near: bottom-center
      top: 235
      left: 0
    }

    application_server: {
      label: "Máy chủ ứng dụng"
      icon: https://cdn-icons-png.flaticon.com/128/2704/2704286.png
      style.multiple: true
      label.near: bottom-center
      top: 468
      left: 0
      width: 469
      height: 102
    }

    storage_server: {
      label: "Máy chủ lưu trữ"
      icon: https://cdn-icons-png.flaticon.com/128/2704/2704286.png
      style.multiple: true
      label.near: bottom-center
      top: 234
      left: 260
      width: 209
      height: 102
    }

    ai_cluster <-> ai_server: Xử lý tác vụ AI siêu nặng
    ai_cluster -> application_server

    ai_cluster -> storage_server

    application_server -> storage_server

    top: 0
    left: 419
    width: 673
    height: 739
    label.near: top-center
    ai_server -> storage_server: Lấy thông tin AI model
  }

  monitor_screen: {
    label: "Màn hình theo dõi"
    icon: https://cdn-icons-png.flaticon.com/128/9926/9926868.png
    style.multiple: false
    label.near: bottom-center
    top: 789
    left: 419
    width: 673
    height: 162
  }

  networking.server_switch -> virtualization_system.ai_cluster
  networking.san_switch -> virtualization_system
  top: 0
  left: 1205
  width: 935
  height: 1038
  networking.server_switch -> monitor_screen
}

current.networking.core_switch -> q_vision_overview.networking.server_switch

**.style.font-size: 22
