label: "Big Data Engineering"

data_lake_architecture: {
  label: "Data Lake Architecture"

  data_ingestion: {
    label: "Data Ingestion"
  }

  data_storage: {
    label: "Data Storage"
  }

  data_processing: {
    label: "Data Processing"

    hadoop_mapreduce: {
      label: "Hadoop MapReduce"
    }

    apache_hive: {
      label: "Apache Hive"
    }

    apache_hbase: {
      label: "Apache HBase"
    }

    pyspark: {
      label: "PySpark"
    }

    dask: {
      label: "Dask"
    }
  }
  grid-rows: 2
}

stream_processing: {
  label: "Stream Processing"

  kafka: {
    label: "Kafka"
  }

  flink: {
    label: "Flink"
  }

  spark_streaming: {
    label: "Spark Streaming"
  }

  apache_storm: {
    label: "Apache Storm"
  }

  apache_samza: {
    label: "Apache Samza"
  }
  grid-rows: 2
}

data_governance: {
  label: "Data Governance"

  data_quality: {
    label: "Data Quality"
  }

  data_lineage: {
    label: "Data Lineage"
  }

  data_security: {
    label: "Data Security"

    encryption_techniques: {
      label: "Encryption Techniques"
    }

    gdpr_compliance: {
      label: "GDPR Compliance"
    }

    rbac: {
      label: "Role-Based Access Control (RBAC)"
    }
  }
  grid-rows: 3
}

data_serialization_formats: {
  label: "Data Serialization Formats"

  avro: {
    label: "Avro"
  }

  parquet: {
    label: "Parquet"
  }

  orc: {
    label: "ORC"
  }
}

messaging_systems: {
  label: "Messaging Systems"

  rabbitmq: {
    label: "RabbitMQ"
  }

  apache_pulsar: {
    label: "Apache Pulsar"
  }
}

programming_languages: {
  label: "Programming Languages"

  scala: {
    label: "Scala"
  }

  java: {
    label: "Java"
  }
}

data_modeling_and_architecture: {
  label: "Data Modeling and Architecture"

  dimensional_modeling: {
    label: "Dimensional Modeling"
  }

  data_vault_modeling: {
    label: "Data Vault Modeling"
  }
}

data_integration_tools: {
  label: "Data Integration Tools"

  apache_nifi: {
    label: "Apache NiFi"
  }

  talend: {
    label: "Talend"
  }
}

data_catalogs_and_metadata_management: {
  label: "Data Catalogs and Metadata Management"

  apache_atlas: {
    label: "Apache Atlas"
  }

  aws_glue_data_catalog: {
    label: "AWS Glue Data Catalog"
  }
}

machine_learning_frameworks: {
  label: "Machine Learning Frameworks"

  spark_mllib: {
    label: "Spark MLlib"
  }

  tensorflow_on_spark: {
    label: "TensorFlow on Spark"
  }
}

grid-rows: 5
