label: "Big Data Cloud Computing"

aws: {
  label: "Amazon Web Services (AWS)"

  aws_emr: {
    label: "Amazon EMR"
  }

  aws_redshift: {
    label: "Amazon Redshift"
  }

  aws_dynamodb: {
    label: "Amazon DynamoDB"
  }

  aws_s3: {
    label: "Amazon S3"
  }

  aws_glue_data_catalog: {
    label: "AWS Glue Data Catalog"
  }
}

azure: {
  label: "Microsoft Azure"

  azure_hdinsight: {
    label: "Azure HDInsight"
  }

  azure_synapse: {
    label: "Azure Synapse Analytics"
  }

  azure_cosmos_db: {
    label: "Azure Cosmos DB"
  }

  azure_data_lake: {
    label: "Azure Data Lake Storage"
  }
}

gcp: {
  label: "Google Cloud Platform (GCP)"

  gcp_dataproc: {
    label: "GCP Dataproc"
  }

  gcp_bigquery: {
    label: "GCP BigQuery"
  }

  gcp_bigtable: {
    label: "GCP Bigtable"
  }

  gcp_cloud_storage: {
    label: "Google Cloud Storage"
  }
}

grid-rows: 3