
cloud_computing: {
    label: "Cloud Computing"
    cloud_platforms: {
      label: "Cloud Platforms"
      aws: {
        label: "Amazon Web Services (AWS)"
      }
      gcp: {
        label: "Google Cloud Platform (GCP)"
      }
      azure: {
        label: "Microsoft Azure"
      }
      ibm_cloud: {
        label: "IBM Cloud"
      }
    }
    services: {
      label: "Services"
      compute_services: {
        label: "Compute Services"
      }
      storage_services: {
        label: "Storage Services"
      }
      database_services: {
        label: "Database Services"
      }
      ai_ml_services: {
        label: "AI and Machine Learning Services"
      }
    }
    cloud_platforms -> services
  }
  