
low_level_programming_electronics: {
    label: "Low-Level Programming and Electronics Engineering"
    programming_languages: {
      label: "Programming Languages"
      cpp: {
        label: "C++"
      }
      cuda: {
        label: "CUDA"
      }
      opencl: {
        label: "OpenCL"
      }
    }
    hardware_device_drivers: {
      label: "Hardware and Device Drivers"
      arduino: {
        label: "Arduino"
      }
      nvidia_jetson: {
        label: "NVIDIA Jetson"
      }
      raspberry_pi: {
        label: "Raspberry Pi"
      }
      rockchip: {
        label: "Rockchip"
      }
    }
    embedded_systems: {
      label: "Embedded Systems"
    }
    programming_languages -> embedded_systems
    hardware_device_drivers -> embedded_systems
  }
  