label: "Natural Language Processing (NLP)"
fundamentals: {
  label: "Fundamentals"

  text_representation: {
    label: "Text Representation"
    text_encoding: "Text Encoding"
  text_embedding: "Text Embedding"
  }   

  text_decoding: {
    label: "Text Decoding"
    text_decoding_techniques: "Text Decoding Techniques"
  }
  text_representation -> text_decoding
}


advanced_topics: {
  label: "Advanced Topics"
  chatbots: {
    label: "Chatbots"
  }
  language_generation: {
    label: "Language Generation"
  }
  sentiment_analysis: {
    label: "Sentiment Analysis"
  }

  text_summarization: "Text Summarization"
}
fundamentals -> advanced_topics
