# roadmap: {
#   label: "Engineering Roadmap"
#   near: top-center
# }

fundamentals: @./fundamentals.d2
computer_vision: @./computer_vision.d2
deep_learning: @./deep_learning.d2
work_in_project: @./work_in_project.d2
data_engineering: @./data_engineering.d2
optimization_techniques: @./optimization_techniques.d2
probability_and_statistic: @./probability_and_statistic.d2
advanced_analytics: @./advanced_analytics.d2
devops_mlops: @./devops_mlops.d2
cloud_computing: @./cloud_computing.d2
low_level_programming_electronics: @./low_level_programming_electronics.d2
apis_web_development: @./apis_web_development.d2
advanced_topics_research: @./advanced_topics_research.d2
additional_recommendations: @./additional_recommendations.d2
natural_language_processing: @./natural_language_processing.d2

*.label:""


work_in_project -> optimization_techniques
deep_learning -> computer_vision
fundamentals -> work_in_project
work_in_project -> data_engineering
work_in_project -> deep_learning
work_in_project -> probability_and_statistic
probability_and_statistic -> advanced_analytics
work_in_project -> devops_mlops
work_in_project -> cloud_computing
computer_vision -> low_level_programming_electronics
work_in_project -> apis_web_development
deep_learning -> natural_language_processing
natural_language_processing -> advanced_topics_research
computer_vision -> advanced_topics_research
advanced_analytics -> advanced_topics_research
additional_recommendations : {near: center-left}
fundamentals:{near: top-center}