label: "Software Design Principles"
architectural_patterns_styles: {
  label: "Architectural Patterns and Styles"
  microservices: {
    label: "Microservices"
  }
  event_driven: {
    label: "Event-Driven"
  }
}

scalability_performance_optimization: {
  label: "Scalability and Performance Optimization"
}

fault_tolerance_high_availability: {
  label: "Fault Tolerance and High Availability Design"
}

security_architecture: {
  label: "Security Architecture"
}


architectural_patterns_styles -> scalability_performance_optimization
architectural_patterns_styles -> fault_tolerance_high_availability
architectural_patterns_styles -> security_architecture
grid-rows: 2