label: "Work in Project and Collaboration"
tools: {
  label: "Tools"
  jira: {
    label: "Jira"
  }
  trello: {
    label: "Trello"
  }
  slack: {
    label: "Slack"
  }
}
methodologies: {
  label: "Methodologies"
  agile: {
    label: "Agile"
  }
  scrum: {
    label: "Scrum"
  }
  kanban: {
    label: "Kanban"
  }
}
version_control: {
  label: "Version Control"
  git: {
    label: "Git"
  }
  github: {
    label: "GitHub"
  }
  gitlab: {
    label: "GitLab"
  }
}

grid-rows: 3
